resources:
  repositories:
  - repository: releaseEngine
    type: github
    endpoint: devopsnights
    name: devopsnights/AzureDevOpsReleaseEngine
    ref: refs/tags/v0.1.1
    
trigger:
  branches:
    include:
    - main
    - feature/*
  paths:
    include:
      - src/development/dotnetCore/*
      
pool:
  vmImage: 'windows-latest'

extends: 
  template: /src/main.yml@releaseEngine
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: /src/development/dotnetCore/examples/variables
        infrastructure:
          enabled: true
        application:
          enabled: true
      azure:
        subscription:
          serviceConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        - uat
        - prd
    resources:
      - name: exampleDotnetCore
        type: dotnetCore
        enabled: true
        deploy:
          type: azureWebApp
          infrastructure:
            enabled: true
            servicePlanName: $(servicePlanName)
            appServiceName: $(appServiceName)
          application:
            enabled: true
