parameters:
- name: settings
  type: object
- name: resource
  type: object  
- name: environment
  type: string

jobs:
  - deployment: ${{ replace(parameters.resource.runName,'-','') }}iac
    displayName: Powershell Modules Deployment
    environment: ${{ parameters.environment }}
    dependsOn: resourceGroupDeploy
    strategy:
      runOnce:
        deploy:
          steps:

            # Push a project
            - task: NuGetCommand@2
              inputs:
                command: 'push'
                packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;!$(Pipeline.Workspace)/**/*.symbols.nupkg'
                nuGetFeedType: 'internal'
                publishVstsFeed: 'devopsnights'
                allowPackageConflicts: true
