parameters:
  - name: resource
    type: object

jobs:
  - job:
    displayName: Powershell Modules - ${{ parameters.resource.runName }} Build Job
    variables:
      - name: moduleVersion
        value: "0.2.0" #TODO: parametrize
         
    steps:
      
      - checkout: self
        persistCredentials: true
      
      # - powershell: |
      #     nuget spec Example.Module
      #     nuget pack ./Example.Module.nuspec
          
      #     # nuget sources Add `
      #     #   -Name "PowershellModules" `
      #     #   -Source "https://wesleycamargo.pkgs.visualstudio.com/_packaging/Powershell/nuget/v3/index.json" `
      #     #   -username "wesleycamargo@outlook.com" `
      #     #   -password "$(System.AccessToken)"
          
      #     # nuget push `
      #     #   -Source "PowershellModules" `
      #     #   -ApiKey AzureDevOpsServices "./Example.Module.0.0.1.nupkg"
      #   workingDirectory: $(Build.SourcesDirectory)/src/development/powershell/psModules/tests/examples/src/Example.Module

      - task: replacetokens@4
        displayName: Replacing tokenized values
        inputs:
          rootDirectory: $(Pipeline.Workspace)
          targetFiles: |
            **/*.psd1
            **/*.nuspec
          encoding: auto
          tokenPattern: azpipelines
          writeBOM: true
          actionOnMissing: warn
          keepToken: false
          actionOnNoFiles: continue
          enableTransforms: false
          useLegacyPattern: false
          enableTelemetry: false
          verbosity: 'detailed'

      - task: NuGetCommand@2
        inputs:
          command: 'pack'
          packagesToPack: '**/Example.Module.nuspec'
          packDestination: '$(build.artifactstagingdirectory)'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: ${{ parameters.resource.runName }}
          publishLocation: 'pipeline'