parameters:
  - name: resource
    type: object

jobs:
  - job: resourceGroupBuildJob
    displayName: IaC - Resource Group Build Job
    steps:

      - template: /src/cloud/azure/bicep/bicep-build-tasks.yml
        parameters:
          resource: ${{ parameters.resource }}
          bicepFilePath: /src/cloud/azure/resourceGroup/bicep/resourceGroup.bicep

      # - task: PublishPipelineArtifact@1
      #   inputs:
      #     targetPath: '$(build.artifactstagingdirectory)'
      #     artifact: governance
      #     publishLocation: 'pipeline'