parameters:
- name: settings
  type: object
- name: resource
  type: object  
- name: environment
  type: string

jobs:

  - template: /src/cloud/azure/bicep/bicep-deploy-jobs.yml  
    parameters:
      settings: ${{ parameters.settings }}                  
      environment: ${{ parameters.environment }}
      resource: ${{ parameters.resource }} 