parameters:
  - name: settings
    type: object

jobs:
  - job: resourceGroupBuildJob
    displayName: IaC - Resource Group Build Job
    steps:

      - template: /src/cloud/azure/bicep/bicep-build-tasks.yml
        parameters:
          resourceType: resourceGroup
          bicepFilePath: /src/cloud/azure/resourceGroup/bicep/resourceGroup.bicep
          outDir: resourceGroup

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: governance
          publishLocation: 'pipeline'