parameters:
- name: settings
  type: object
- name: resource
  type: object  
- name: environment
  type: string

jobs:
        
  - ${{ if and(eq(parameters.settings.deploy.infrastructure.enabled, 'true'), eq(parameters.resource.deploy.infrastructure.enabled, 'true')) }}:
  


    - deployment: ${{ parameters.resource.jobName }}
      displayName: IaC -  ${{ parameters.resource.name }} - Azure Deployment
      environment: ${{ parameters.environment }}
      ${{ if ne(parameters.resource.dependsOn,'') }}:
        dependsOn: ${{ parameters.resource.dependsOn }}
      variables:
        ${{ if ne(parameters.resource.deploy.type,'') }}:
          bicepFile: ${{ parameters.resource.deploy.type }}.json
        ${{ else }}:  
          bicepFile: ${{ parameters.resource.type }}.json
      strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                  # $var = "$(Pipeline.Workspace)/${{ parameters.resource.name }}-iac/${{ variables.bicepFile }}.json"
                  # Write-Host $var

                  Write-Host "bicep path"

                  Write-Host "$(Pipeline.Workspace)/${{ parameters.resource.name }}-iac/${{ variables.bicepFile }}"

                  Get-ChildItem $(Pipeline.Workspace) -recurse
              
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: Creating '${{ parameters.resource.name }}' by IaC
                inputs:
                  ${{ if eq(parameters.resource.type, 'resourceGroup') }}:
                    deploymentScope: 'Subscription'
                  azureResourceManagerConnection: '${{ parameters.settings.azure.subscription.serviceConnection }}'
                  subscriptionId: ${{ parameters.settings.azure.subscription.subscriptionId }}
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: ${{ parameters.settings.azure.resourceGroup.name }}
                  location: ${{ parameters.settings.azure.resourceGroup.location }}
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/${{ parameters.resource.name }}-iac/${{ variables.bicepFile }}'
                  overrideParameters: ${{ parameters.resource.deploy.infrastructure.overrideParameters }}
                  deploymentMode: 'Incremental'
                  deploymentOutputs: 'ArmOutputs'