parameters:
  - name: resource
    type: object
jobs:
  - job:
    displayName: IaC - Azure App Service Build Job
    steps:
      - powershell: |
          Get-ChildItem -Path env:

      - template: /src/cloud/azure/bicep/bicep-build-tasks.yml
        parameters:
          resourceType: appService
          bicepFilePath: /src/cloud/azure/appService/bicep/appService.bicep

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(build.artifactstagingdirectory)
          artifact: ${{ parameters.resource.name }}-iac
          publishLocation: pipeline