parameters:
  - name: resource
    type: object
jobs:
  - job:
    displayName: IaC - Azure App Service Build Job
    steps:

      - template: /src/cloud/azure/bicep/bicep-build-tasks.yml
        parameters:
          resourceType: appService
          bicepFilePath: /src/cloud/azure/appService/bicep/appService.bicep
