resources:
  repositories:
  - repository: ReleaseEngine
    type: github
    endpoint: devopsnights
    name: devopsnights/AzureDevOpsReleaseEngine
    ref: refs/heads/feature/overrideImprovements

trigger:
  branches:
    include:
    - main
    - feature/basicWebApp
  paths:
    include:
      - src/solutions/azure/basicWebApplication/examples/*
      
pool:
  vmImage: 'windows-latest'

extends: 
  template: /src/main.yml@releaseEngine
  parameters:
    settings:
      build:
        enabled: true
      deploy:
        enabled: true
        variablesDirectory: /src/solutions/azure/basicWebApplication/examples/variables
        infrastructure:
          enabled: true
        application:
          enabled: false
      azure:
        subscription:
          serviceConnection: $(serviceConnection)
          subscriptionId: $(subscriptionId)
        resourceGroup:
          name: $(resourceGroupName)
          location: $(location)
          new: true
      environments:
        - dev
        # - uat
        # - prd
    resources:

      - name: resourceGroup
        type: resourceGroup
        enabled: true
        deploy:
          infrastructure:
            enabled: true
            location: $(location)
            name: $(resourceGroupName)
            overrideParameters: >
              -resourceGroupLocation $(location)
              -resourceGroupName $(resourceGroupName)            

      - name: exampleDotnetCore
        type: dotnetCore
        enabled: true
        deploy:
          type: appService
          infrastructure:
            enabled: true
            servicePlanName: $(servicePlanName)
            appServiceName: $(appServiceName)
            overrideParameters: >
              -servicePlanName $(servicePlanName)
              -siteName $(appServiceName)              
          application:
            enabled: true

      - name: exampleBasicWebApp
        type: basicWebApplication
        enabled: true
        deploy:
          infrastructure:
            enabled: true
            sqlAdminUserName: wesley
            sqlAdminPassword: $(sqlAdminPassword)
            sqlEmailAddress: 'wesley@releaseengine.com'
          application:
            enabled: false
